{% set name = "ophyd" %}
{% set version = "1.9.0" %}
{% set sha256 = "a7ab41c5be9e131f880b664a50e13bfc432631ab581df4788429ee59e0fe68a6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - caproto
    - networkx >=2.5
    - numpy
    - pint
    - pyepics >=3.4.2

test:
  imports:
    - {{ name }}
    - {{ name }}.utils
    - {{ name }}.areadetector
    - {{ name }}.sim

about:
  home: https://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Ophyd - EPICS Client Abstractions
  description: Ophyd - EPICS Client Abstractions
  doc_url: https://blueskyproject.io/ophyd
  dev_url: https://github.com/bluesky/ophyd

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - danielballan
    - klauer
    - mrakitin
    - tacaswell
    - zllentz
