{% set name = "ophyd" %}
{% set version = "1.10.5" %}
{% set sha256 = "668d24af34a0b91bb5c5b076d216111087a86ed262bb6aa2c7af407af0141a75" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - caproto
    - networkx >=2.5
    - numpy
    - opentelemetry-api
    - pint
    - pyepics >=3.4.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name }}
    - {{ name }}.utils
    - {{ name }}.areadetector
    - {{ name }}.sim

about:
  home: https://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Ophyd - EPICS Client Abstractions
  description: Ophyd - EPICS Client Abstractions
  doc_url: https://blueskyproject.io/ophyd
  dev_url: https://github.com/bluesky/ophyd

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - danielballan
    - klauer
    - mrakitin
    - tacaswell
    - zllentz
