{% set name = "ophyd" %}
{% set version = "1.5.2" %}
{% set sha256 = "ea78821936ee629717677a0669c7c47fd8ee26ba47d5f1b0cd07fdb4a67dd313" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - networkx
    - numpy
    - pyepics >=3.4.2
    - setuptools

test:
  imports:
    - {{ name }}
    - {{ name }}.utils
    - {{ name }}.areadetector
    - {{ name }}.sim

about:
  home: https://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Ophyd - EPICS Client Abstractions
  description: Ophyd - EPICS Client Abstractions
  doc_url: https://blueskyproject.io/ophyd
  dev_url: https://github.com/bluesky/ophyd

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - danielballan
    - hhslepicka
    - klauer
    - mrakitin
    - tacaswell
    - zllentz
