{% set name = "ophyd" %}
{% set version = "1.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef63cc291a34d55823ec2f62be91991786ce4b9100e374df097b785d849466c3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - caproto !=1.2.0  # known-bad version
    - networkx >=2.5
    - numpy
    - opentelemetry-api
    - packaging
    - pint
    - pyepics >=3.4.2

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - {{ name }}
    - {{ name }}.utils
    - {{ name }}.areadetector
    - {{ name }}.sim

about:
  home: https://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Ophyd - EPICS Client Abstractions
  description: Ophyd - EPICS Client Abstractions
  doc_url: https://blueskyproject.io/ophyd
  dev_url: https://github.com/bluesky/ophyd

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - danielballan
    - klauer
    - mrakitin
    - tacaswell
    - zllentz
