{% set name = "ophyd" %}
{% set version = "1.10.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3637a03a874fd9b4917d5089b738060dea7cd57c4445f21e2275e2b7624b007

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - caproto <1.2.0  # Temp fix before we figure out the issue in ophyd.
    - networkx >=2.5
    - numpy
    - opentelemetry-api
    - packaging
    - pint
    - pyepics >=3.4.2

test:
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - {{ name }}
    - {{ name }}.utils
    - {{ name }}.areadetector
    - {{ name }}.sim

about:
  home: https://blueskyproject.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Ophyd - EPICS Client Abstractions
  description: Ophyd - EPICS Client Abstractions
  doc_url: https://blueskyproject.io/ophyd
  dev_url: https://github.com/bluesky/ophyd

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - danielballan
    - klauer
    - mrakitin
    - tacaswell
    - zllentz
