appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XW2pHh6gq8cfoIR2vQ68ZcA47Z+J0jWS+fbF2ybhRmM1BwgI7LsYpMtCF5WesFbcNqKHGB1UE/iWCWRvyj4Jw8ssKDbL2zJDq1edEsBBhCfJOv21i1+LqbVNwvm3/QDLr+rsp3th+hzjgsZQhl5WDSlaF/PfkPHxmXiiUwACycWyd1akJWcvlzg539ViQMQ4fXMw1YGDcvgLIf8c7At+2GioTfNE1ah2w7rsM6NSVQwevb6ZKZlpI26EjCFvV2m6uS4+VjZYznmxnPM8Va3zRpVIxZn3Ze+pWaiq7rFSZ0iE5QXvBmw74EjW8PDfiK+SwyUQD8y346e+dtYO00nu2o37lnYeX1cvty7B9IKuwmq2IOJk7DWmx+29q/iHzvunsTT1d9yRh1ITnSnRbwCcb8TueO2ZVxFdqD2w6y5jNx1KQyinOnYAOLFN+BWDC97LBtnio8T+gdLLYcLtiUBGg64SxV+hk/IYkA8rA8UAqh219uoq71gDAALB/Bp1rbE8F3yU5IwnzyQJL6s9Ur9MYGZgc005mxqKs6Sf1kmrFSNv+dwXbyDjzU/ibwMGmdu2XU+YJAX6mQgrcK/mfUHLNw+JJE78hjJaLTfEciugtTUZbMXOIyQyvnU1j/kN+kMoDVfsrz4j4QyKgYqwF6uFdor/22pvmeaNNrjHem7icec=}
